shorten.settings:
  type: mapping
  label: Settings
  mapping:
    shorten_cache_clear_all:
      type: boolean
    shorten_invisible_services:
      type: string
    shorten_service:
      type: string
    shorten_service_backup:
      type: string
    shorten_www:
      type: boolean
    shorten_method:
      type: string
    shorten_cache_duration:
      type: integer
    shorten_cache_fail_duration:
      type: integer
    shorten_budurl:
      type: string
    shorten_ez:
      type: string
    shorten_bitly_login:
      type: string
    shorten_bitly_key:
      type: string
    shorten_googl:
      type: string
    shorten_fwd4me:
      type: string
    shorten_timeout:
      type: integer
    shorten_show_service:
      type: boolean
    shorten_use_alias:
      type: integer
    shorten_cligs:
      type: string
    shorten_redirec:
      type: string
