<?php
use Drupal\Core\Block\BlockBase;
use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity;
use Drupal\Core\Controller\ControllerBase;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\JsonResponse;
use Drupal\Core\Database;
use Drupal\node\Entity\Node;
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation;
use Drupal\Component\Render\FormattableMarkup;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\OpenModalDialogCommand;
use Drupal\user\Entity\User;
use Drupal\Core\Session\AccountInterface;
use Symfony\Component\HttpFoundation\Request;


function get_related_data($uid){
  $uid = 1;
  global $base_url;
  $nids = \Drupal::entityQuery('node')
  ->condition('status', 1)
  ->condition('type', 'blog_post')
  ->condition('uid',$uid)
  ->execute();
  $blog = Node::loadMultiple($nids);

  $nids = \Drupal::entityQuery('node')
  ->condition('status', 1)
  ->condition('type', 'd_product')
  ->condition('uid',$uid)
  ->execute();
  $o = '';
  $product = Node::loadMultiple($nids);
  if(!empty($blog) || !empty($product)){
    $o ='<nav role="navigation" class="business-menu">';
    $o .= '<ul class="nav navbar-nav main-menu clearfix business-menu">';
    if(!empty($blog)){
      $o .= '<li class="nav-item menu-item--expanded dropdown"><a href="/blog" class="nav-link">Blog</a>
          <a href="#" class="menu-dropdown-icon" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true"></a><ul class="dropdown-menu">';
      foreach ($blog as $key => $node) {
        $alias = \Drupal::service('path.alias_manager')->getAliasByPath('/node/'.$node->nid->value);
        $title = $node->getTitle();
        $o .= '<li class="dropdown-item"><a href="'.$base_url.$alias.'">'.t($title).'</a></li>';
      }
      $o .= '</ul></li>';
    }

    if(!empty($product)){
      $o .= '<li class="nav-item menu-item--expanded dropdown"><a href="/products" class="nav-link">Products</a>
          <a href="#" class="menu-dropdown-icon" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true"></a><ul class="dropdown-menu">';
      foreach ($product as $key => $node) {
        $alias = \Drupal::service('path.alias_manager')->getAliasByPath('/node/'.$node->nid->value);
        $title = $node->getTitle();
        $o .= '<li class="dropdown-item"><a href="'.$base_url.$alias.'">'.t($title).'</a></li>';
      }
      $o .= '</ul></li>';
    }
    $o .= '</ul>';
    $o .='</nav>';
  }
  $form['#markup'] = $o;
  $form['#cache']['max-age'] = 0;
  return $form;
}
