<?php

/**
 * @file
 * Allows Custom code custom_feeds_import module.
 */
use Drupal\comment\Entity\Comment;
use Drupal\node\Entity\Node;
use Drupal\Core\Mail\MailManagerInterface;
use Drupal\user\Entity\User;
use Drupal\Core\Url;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Component\Utility\Html;
use \Drupal\file\Entity\File;

function get_categories_names($vid = 'category'){
	$term_data = [];
	$terms =\Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid);
	foreach ($terms as $term) {
	 $term_data[] = array(
	  'name' => strtolower($term->name),
	  'tid' => $term->tid
	 );
	}
	return $term_data;
}

function get_data($url){
	try {
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($ch, CURLOPT_URL, $url);
		$result = curl_exec($ch);
		curl_close($ch);

		$obj = json_decode($result);
		return $obj;
	}
	catch (RequestException $e) {
	   \Drupal::logger('custom_feeds_import')->error('Api fetch error.');
	}
	return FALSE;
}

/**
 * Implements hook_cron().
 */
function custom_feeds_import_cron() {  
  $last_run = \Drupal::state()->get('custom_feeds_import.last_run', 0);
  $config = \Drupal::config('custom_feeds_import.settings');
  $uid = $config->get('custom_feeds_import_uid');
  $keyApi = $config->get('custom_feeds_import_keyApi');
  if ((REQUEST_TIME - $last_run) > 3600) {

		$queue = \Drupal::queue('custom_feeds_import');
		$queue->createQueue();
  	    $categories = get_categories_names();
  	    foreach ($categories as $key => $term) {
  	    		$uri = 'https://newsapi.org/v2/everything?q='.$term['name'].'&apiKey='.$keyApi;
			    if($data = get_data($uri)){
			    	if(!empty($data->articles)){
			    		foreach ($data->articles as $article) {
			    			$title = $description = $url = $author = $link = $source = "";
			    			if(!empty($article->title)){
			    				$title = ucfirst($article->title);
			    			}
			    			if(!empty($article->urlToImage)){
			    				$url = $article->urlToImage;
			    			}
			    			if(!empty($article->url)){
			    				$link = $article->url;
			    			}
			    			if(!empty($article->description)){
			    				$description = $article->description;
			    			}
			    			if(!empty($article->author)){
			    				$author = $article->author;
			    			}
			    			if(!empty($article->source) && !empty($article->source->name)){
			    				$source = $article->source->name;
			    			}
			    			$item = (object) ['uid' => $uid, 'title' => $title, 'body' => $description, 'tid' => $term['tid'], 'url' => $url, 'author' => $author, 'link' => $link, 'source' => $source];

							if(!empty($article->urlToImage)){
								$queue->createItem($item);
							}
			    		}
			    	}
			    }
  	    }
    // Update last run.
    \Drupal::state()->set('custom_feeds_import.last_run', REQUEST_TIME);
  }
}
